### ISSUE TITLE
《Android Jetpack开发：原理解析与应用实战》 源码

### ISSUE THREAD

**Issue by liucxu** [huanglinqing123/huanglinqing123#1]
你好,刚买了你的书，在刚看到第二章Lifecycle的时候，想找下书上的相关源码，按照你书上写的**huanglinqing123**没找到，
按照你说的到**华章图书**页面也没找到相关源码，所以我想问下你这本书对应的全部源码到底在什么地方可以全部看到，谢谢。

**Comment by huanglinqing123** [comment]
你好，欢迎加我微信hzx1306214077邀你进去入读者群，所有源码在读者群里。以后有其他问题也方便交流



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月22日(周五) 晚上11:17
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [huanglinqing123/huanglinqing123] 《Android Jetpack开发：原理解析与应用实战》 源码 (Issue #1)




 
你好,刚买了你的书，在刚看到第二章Lifecycle的时候，想找下书上的相关源码，按照你书上写的huanglinqing123没找到，
 按照你说的到华章图书页面也没找到相关源码，所以我想问下你这本书对应的全部源码到底在什么地方可以全部看到，谢谢。

**Comment by shesio** [comment]
没源码吗？
